### ISSUE TITLE
Could not be found my github account

### ISSUE THREAD

**Issue by MohamedRejeb** [oliyh/stardev-feedback#13]
My account was appearing and everything works fine, a week ago I changed my github username and now the new username is not recognized by stardev io and the old one still appearing.

![Screenshot 2023-05-05 at 3 10 03 PM](https://user-images.githubusercontent.com/41842296/236481710-2cd2de55-7f58-4463-bb71-75c850d91642.png)

**Comment by oliyh** [comment]
Hi, thanks for reporting this.

The site has not been syncing with Github for the past week or two whilst I am transitioning to the new 'next id' provided by the Github API. Once this is complete (another week or so) you should see your new username reflecting (which should also fix your gravatar).

I'll update you here when it's ready.
Cheers

**Comment by oliyh** [comment]
Hi,

The work is now complete and your profile was synced a few minutes ago, it now has the correct username:
https://stardev.io/developers/MohamedRejeb (amazing Kotlin stats, by the way!)

Let me know if you have any further issues, and thanks for your feedback.
