### ISSUE TITLE
Take so much time to resync with the latest Github data

### ISSUE THREAD

**Issue by aminekarimii** [oliyh/stardev-feedback#14]
Hello 👋🏽

stardev is a great website, the only problem is the time taking to update the used data from GitHub.
I have queued a re-sync request on May 5, 2023, but there is still no update.

**Comment by oliyh** [comment]
Hi, thanks for reporting this.

The site has not been syncing with Github for the past week or two whilst I am transitioning to the new 'next id' provided by the Github API. Once this is complete (another week or so) this will be fixed.

I'll update you here when it's ready.
Cheers

**Comment by oliyh** [comment]
Hi,

This work is now complete, your profile was synced a few minutes ago. Could you check and let me know if it looks good to you? https://stardev.io/developers/aminekarimii

Thanks
