### ISSUE TITLE
What qualifies to be in the lsit

### ISSUE THREAD

**Issue by NAVFreak** [oliyh/stardev-feedback#17]
Interesting project!
However, I couldn't find details on which metrics it uses for quailification and programming language.
I saw the list and I know there are way more repos developers that should be included.

**Comment by oliyh** [comment]
Hi, thanks!

Every account on GitHub is included. Repos are included when they are created directly by the account (i.e. forks are not included). Anything with more than zero stars is included in a ranking list.

The language of each repo is determined by GitHub - they have a tool called Linguist which calculates this. If you think something has been detected incorrectly you can give hints to Linguist to help it.

Location is derived from the location on the GitHub account, and geocoded by Nominatim.

One caveat is that sometimes (usually on the largest accounts with the most repos) GitHub's API fails in such a way that makes it hard to determine if the account has been deleted. This means that sometimes the largest and most popular repos and accounts will disappear from the rankings until a resync can pull them in again. This needs to be improved! You can still find these accounts using the search, their pages will be marked as 'archived'.

Hope this answers all your questions.
Cheers
