### ISSUE TITLE
Badges are not loading!

### ISSUE THREAD

**Issue by harsh8088** [oliyh/stardev-feedback#18]
Badge:

```
<p align="left">
<a href="https://stardev.io/developers/harsh8088"><img alt="Check out harsh8088's profile on stardev.io" src="https://stardev.io/developers/harsh8088/badge/languages/locality.svg" /></a>
</p>
```

Output:
<img width="807" alt="Screenshot 2024-06-10 at 11 56 00 AM" src="https://github.com/oliyh/stardev-feedback/assets/7496696/28496e69-c7bf-4f0b-8079-7d48e79da5fa">

**Comment by oliyh** [comment]
Hello,

The site is currently being hammered by Facebook. I'm trying to work out how to rate limit or block it!

Cheers

**Comment by harsh8088** [comment]
Thanks for letting us know.

**Comment by oliyh** [comment]
Facebook blocked, you should find things are better now!

Thanks for the report.
