### ISSUE TITLE
Not all developers listed, and some are gone.

### ISSUE THREAD

**Issue by xing1357** [oliyh/stardev-feedback#2]
Upon using google search, there is an entry with my name in stardev, but the page doesn't exist.

**Comment by oliyh** [comment]
Hi, thanks for reporting this, I'll look into it.

**Comment by oliyh** [comment]
Hi,

I think an error must have occurred when re-syncing users with Github. They could not be retrieved and were therefore marked as deleted, which is why they no longer appear on the site. I'll work on a fix and to get them reimported.

Thanks

**Comment by xing1357** [comment]
Hey,
Sorry to bother you, some of the developers are back, mine still isn't.
Thanks,
Harvey

**Comment by oliyh** [comment]
Hello,

Yes, I've fixed some bugs and I'm resyncing all users. It will take a bit of time, it's up to October 2014 and I think you joined in 2020 or 2021 so it might be a few more days at least. I'll let you know here when it's finished.

**Comment by xing1357** [comment]
Hmm... its been a while, how has the syncing gone?

**Comment by oliyh** [comment]
Up to Feb 2019! There are nearly a million new users a month at this point and that number keeps growing, so it will go slower as it progresses. Might still be a week or more before it manages to get to you...

**Comment by oliyh** [comment]
Hi,

The sync is up to October 2020, your profile appears now: https://stardev.io/developers/xing1357

Thanks for reporting the issue!
