### ISSUE TITLE
Starred forked repos

### ISSUE THREAD

**Issue by jdegand** [oliyh/stardev-feedback#21]
Forks with stars are not counted.  GitHub API makes no distinction or would this require a separate API call ?

**Comment by oliyh** [comment]
Hi,

This is by design - only repositories you "own" get counted, and this does not include forks. The GraphQL query is:

```
repositories(isFork: false, privacy: PUBLIC, ownerAffiliations: OWNER) {
     ...repositoryFields
}
```
