### ISSUE TITLE
I can't see my repository

### ISSUE THREAD

**Issue by anasty17** [oliyh/stardev-feedback#3]
Hi, hope everything is fine.

Something wrong, number of my Repositories is zero. Try search on my name, then check my github pinned repository.

Thanks in advance

**Comment by oliyh** [comment]
Hi,

Thanks for reporting, I'll investigate.

Cheers

**Comment by oliyh** [comment]
Hi,

It should work, there may have been a temporary issue with the last time your profile was pulled from Github. It will be synced again soon, unfortunately I don't have a way of manually syncing at the moment.

**Comment by anasty17** [comment]
Okay thanks 😊

**Comment by anasty17** [comment]
Hi again,

Problem still exits after maintenance

**Comment by oliyh** [comment]
Hello,

Yes, sync hasn't happened on your profile yet. The maintenance was to upgrade to Ubuntu 22 :)

I'm hoping to add a feature to allow you to request a resync on your profile, I'll let you know when that's ready.

**Comment by anasty17** [comment]
Ok thanks :)

**Comment by oliyh** [comment]
Hi,

I've added "last updated" at the bottom of the developer page, so you can see when the last sync happened. Yours currently is `2022-08-25T12:44:19.496556591Z`. It will be a while before it syncs again automatically, I'm still going to work on the manual sync feature and will keep this thread updated.

Thanks

**Comment by anasty17** [comment]
Thanks for your hard work 👍

**Comment by oliyh** [comment]
Hello,

The feature is here! If you visit your developer page https://stardev.io/developers/anasty17 you will see a 'Re-sync' link at the bottom next to the 'Last updated' time.

If you follow that link you will be directed to sign in with Github and allow stardev.io to see your identity (no other permissions needed). After this, you should find a button allowing you to request a manual sync.

I'd be grateful if you could try it out and let me know any feedback you have?

Thanks

**Comment by anasty17** [comment]
Hello,

I have requested the re-sync

Thanks

**Comment by oliyh** [comment]
Looks good now!

It must have been a transient error before.

Note that the badges are cached for 24 hours so it should update this time tomorrow.

Hope the process was smooth, in the end. Thanks for your patience and feedback.

Cheers

**Comment by anasty17** [comment]
Sync done! It took less than 2 hours
Thanks
