### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by iamnijat** [oliyh/stardev-feedback#4]
I have been experiencing this issue for many hours, if you fixed that, I would appreciate it

**Comment by oliyh** [comment]
Hi,

Thanks for your message. The hosting company had an outage in one of their datacenters. Everything seems back online now!

**Comment by oliyh** [comment]
But as I write this I see there is another outage. The company says it is an issue with bandwidth and they're working to get it resolved.

**Comment by iamnijat** [comment]
Alright, thanks for feedback

**Comment by oliyh** [comment]
The root cause is apparently now resolved, thanks for the report. Hopefully you'll have no further issues but please let me know if you do.
