### ISSUE TITLE
This record has been archived Issue

### ISSUE THREAD

**Issue by develNerd** [oliyh/stardev-feedback#6]
I get **This record has been archived** for my github username
<img width="1332" alt="Screenshot 2022-11-23 at 7 04 18 PM" src="https://user-images.githubusercontent.com/37780207/203627632-b51e95db-ace0-45c7-826e-d61b228b2775.png">

**Comment by oliyh** [comment]
Hello,

Sometimes the GitHub API returns transient errors which are fairly indistinguishable from the error returned when a user has deleted their GitHub account.

If you click the 'Resync' link right at the bottom of the page it will schedule a fetch from GitHub, your profile should be restored within a few hours. Let me know if you still have issues after that.

Cheers

**Comment by develNerd** [comment]
Hello,

Thank you for your reply. Would do exactly that and give you a feedback

**Comment by oliyh** [comment]
Hello,

Looks good to me today. Congrats on your amazing Kotlin rank!

**Comment by develNerd** [comment]
Hello, 

Yes it looks okay now. Thanks
