### ISSUE TITLE
Account Issue

### ISSUE THREAD

**Issue by muhammadtalhasultan** [oliyh/stardev-feedback#7]
My Account has been showing unknown for the last few days previously it was showing right Pakistan and coming in the list below as well.
https://stardev.io/developers/muhammadtalhasultan
https://stardev.io/top/developers/dart/in/pakistan?page=1

**Comment by oliyh** [comment]
Hi,

It still shows as Pakistan / Islamabad for me but you have "This record has been archived" which is when there is trouble reading from Github and it's assumed your account has been deleted - this removes you from the ranking sets.

If you click the "Re-sync" link at the bottom of the page you can request to read again from Github which should fix the issue.

Let me know if this helps, cheers
